// State
import { createSlice, createAsyncThunk } from "@reduxjs/toolkit";
import { RootState } from "../store";
// Types
import { ITicketCardAPI } from "../components/ui/ticket-card/types";
// API
import TicketCards from "../api/ticketCardsAPI";

export enum TicketCardsStatus {
  "IDLE" = "idle",
  "LOADING" = "loading",
  "SUCCEEDED" = "suceeeded",
  "FAILED" = "failed",
}

export interface TicketCardsState {
  ticketCardsList: ITicketCardAPI[] | [];
  status: TicketCardsStatus;
  error: string;
}

const initialState: TicketCardsState = {
  ticketCardsList: [],
  status: TicketCardsStatus.IDLE,
  error: "",
};

// Fetching a list of ticket cards
export const fetchTicketCards = createAsyncThunk(
  "ticketCards/fetchTicketCards",
  async () => {
    const response = await TicketCards.list();
    // The value we return becomes the `fulfilled` action payload
    return response.data;
  }
);

// @ts-ignore
export const ticketCardsSlice = createSlice({
  name: "ticketCards",
  initialState,
  reducers: {},
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(fetchTicketCards.pending, (state) => {
        state.status = TicketCardsStatus.LOADING;
      })
      .addCase(fetchTicketCards.fulfilled, (state, action) => {
        state.status = TicketCardsStatus.SUCCEEDED;
        // @ts-ignore
        state.ticketCardsList = state.ticketCardsList.concat(action.payload);
      })
      .addCase(fetchTicketCards.rejected, (state, action) => {
        state.status = TicketCardsStatus.FAILED;
        state.error = action.error.message as string;
      });
  },
});

export const selectTicketCards = (state: RootState) =>
  // @ts-ignore
  state.ticketCards.ticketCardsList;

export default ticketCardsSlice.reducer;
